CREATE DATABASE hr
GO 

USE hr
GO 

CREATE TABLE regions
(
		REGION_ID INT PRIMARY KEY,
		REGIONS_NAME VARCHAR(25)
)
GO 

CREATE TABLE countries
(
	COUNTRATY_ID CHAR(2) PRIMARY KEY,
	COUNTARY_NAME VARCHAR(40),
	REGION_ID INT
	FOREIGN KEY (REGION_ID) REFERENCES [dbo].[regions](REGION_ID)
)
GO

CREATE TABLE  locations
(
	LOCATION_ID INT PRIMARY KEY,
	STREET_ADDRESS VARCHAR(25),
	POSTAL_CODE VARCHAR(12),
	CITY VARCHAR(30),
	STATE_PROVINOE VARCHAR(12),
	COUNTRATY_ID CHAR(2)

	FOREIGN KEY (COUNTRATY_ID) REFERENCES [dbo].[countries] (COUNTRATY_ID)
)
GO

CREATE TABLE jops 
(
	JOP_ID VARCHAR(10) PRIMARY KEY,
	JOP_TITLE VARCHAR(35),
	MIN_SALARY INT,
	MAX_SALRY INT
)
GO

CREATE TABLE departments
(
	DEPRATMENT_ID INT PRIMARY KEY,
	DEPARTMENT_NAME VARCHAR(30),
	MANAGER_ID INT,
	LOCATION_ID INT

	FOREIGN KEY (LOCATION_ID) REFERENCES [dbo].[locations](LOCATION_ID)

)
GO

CREATE TABLE employess
(
	EMPLOYEE_ID INT PRIMARY KEY,
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(25),
	EMAIL VARCHAR(25),
	PHONE_NUMBER VARCHAR(20),
	HIRE_DATE DATE,
	JOP_ID VARCHAR(10),
	SALARY INT,
	COMMISSION_PCT INT,
	MANGAER_ID INT,
	DEPARTMENT_ID INT

	FOREIGN KEY (JOP_ID) REFERENCES [dbo].[jops](JOP_ID),
	FOREIGN KEY (DEPARTMENT_ID) REFERENCES [dbo].[departments](DEPRATMENT_ID)
)
GO
CREATE TABLE jop_history
(
	EMPLOYEE_ID INT ,
	START_DATEE DATE ,
	END_DATE DATE,
	JOP_ID VARCHAR(10),
	DEPARTMENT_ID INT
	PRIMARY KEY (EMPLOYEE_ID,START_DATEE)
	FOREIGN KEY (JOP_ID) REFERENCES [dbo].[jops](JOP_ID),
	FOREIGN KEY (DEPARTMENT_ID) REFERENCES [dbo].[departments] (DEPRATMENT_ID)
)
GO
CREATE TABLE jop_grades
(
	GRADE_LEVEL VARCHAR(2),
	LOWEST_SAL INT,
	HIGHEST_SAL INT
)